"use client";

import { useState } from "react";
import Link from "next/link";
import {
  standup,
  titles,
  escalationDrafts,
  analyticsRollups,
  fmtMoney,
  fmtDate,
} from "@/lib/data";
import Badge from "./Badge";
import KpiCard from "./KpiCard";
import Sparkline from "./Sparkline";
import EscalationModal from "./EscalationModal";
import {
  AlertTriangle,
  CircleDot,
  Send,
  ArrowUpRight,
  Sparkles,
  ChevronRight,
} from "lucide-react";

const STATUS_LABEL = {
  on_track: "On track",
  at_risk: "At risk",
  blocked: "Blocked",
  delayed: "Delayed",
};

const SEVERITY_TONE = {
  high: "red",
  medium: "amber",
  low: "neutral",
};

export default function DailyStandup() {
  const [activeDraftId, setActiveDraftId] = useState(null);

  const activeDraft = escalationDrafts.find(
    (d) => d.draft_id === activeDraftId
  );

  const k = standup.kpi_top_strip;

  return (
    <div className="px-4 md:px-6 lg:px-8 py-5 md:py-7 max-w-[1500px] mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-end justify-between gap-4 flex-wrap">
        <div>
          <div className="text-[11px] uppercase tracking-wider text-ink-500 font-semibold flex items-center gap-2">
            <Sparkles className="h-3 w-3 text-accent-primary" />
            Daily Standup · {fmtDate(standup.standup_date, { year: true })}
          </div>
          <h1 className="display text-[28px] md:text-[34px] font-bold tracking-tight mt-1">
            Where the portfolio is today.
          </h1>
        </div>
        <Link
          href="/inbox"
          className="text-[12px] text-accent-primary font-medium flex items-center gap-1 hover:underline"
        >
          Open AI Inbox <ArrowUpRight className="h-3 w-3" />
        </Link>
      </div>

      {/* Portfolio health summary (Claude-generated) */}
      <section className="panel p-5 md:p-6 relative overflow-hidden">
        <div className="absolute top-0 left-0 h-1 w-full bg-gradient-to-r from-accent-primary via-accent-violet to-accent-primary" />
        <div className="flex items-start gap-3">
          <div className="h-8 w-8 rounded-lg bg-accent-primary/10 text-accent-primary flex items-center justify-center shrink-0">
            <Sparkles className="h-4 w-4" />
          </div>
          <div className="min-w-0">
            <div className="text-[11px] uppercase tracking-wider text-ink-500 font-semibold">
              Portfolio health roll-up — generated by Claude
            </div>
            <p className="text-[14.5px] md:text-[15px] leading-relaxed mt-2 text-ink-900">
              {standup.portfolio_health_summary}
            </p>
          </div>
        </div>
      </section>

      {/* KPI top strip */}
      <section className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
        <KpiCard
          label="Tickets due today"
          value={k.tickets_due_today}
          hint={`${k.tickets_at_risk_this_week} at risk this week`}
        />
        <KpiCard
          label="Portfolio D30"
          value={`${k.avg_d30_retention_pct}%`}
          trend={k.avg_d30_retention_trend}
          delta={`${k.avg_d30_retention_delta_pp > 0 ? "+" : ""}${
            k.avg_d30_retention_delta_pp
          }pp`}
        />
        <KpiCard
          label="Wishlist velocity / wk"
          value={k.portfolio_wishlist_velocity_weekly.toLocaleString()}
          trend={k.portfolio_wishlist_velocity_trend}
          delta={`+${k.portfolio_wishlist_velocity_delta_pct}%`}
        />
        <KpiCard
          label="Avg review score"
          value={`${k.avg_review_score_pct}%`}
          trend={k.avg_review_score_trend}
          delta={`+${k.avg_review_score_delta_pp}pp`}
        />
        <KpiCard
          label="Budget pacing"
          value={`${k.budget_pacing_spent_pct}%`}
          hint={`Quarter ${k.budget_pacing_quarter_through_pct}% through`}
        />
        <KpiCard
          label="Decisions pending"
          value={analyticsRollups.decisions_pending_director.length}
          hint="Awaiting Davide call"
        />
      </section>

      {/* By title grid */}
      <section>
        <div className="flex items-center justify-between mb-3">
          <h2 className="section-title">By title</h2>
          <Link
            href="/titles"
            className="text-[11px] text-accent-primary font-medium hover:underline flex items-center gap-1"
          >
            All titles <ChevronRight className="h-3 w-3" />
          </Link>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3">
          {standup.by_title.map((b) => {
            const t = titles.find((x) => x.title_id === b.title_id);
            if (!t) return null;
            const flagged = b.claude_blurb.includes("⚠");
            return (
              <Link
                key={b.title_id}
                href={`/titles/${t.franchise_slug}`}
                className="panel p-4 hover:shadow-md hover:border-ink-300 transition-all group block"
              >
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2 min-w-0">
                    <span
                      className="h-2.5 w-2.5 rounded-full shrink-0"
                      style={{ backgroundColor: t.brand_color }}
                    />
                    <span className="text-sm font-semibold truncate">
                      {t.title_name}
                    </span>
                  </div>
                  <Badge status={t.campaign_status} size="xs">
                    {STATUS_LABEL[t.campaign_status] || t.campaign_status}
                  </Badge>
                </div>
                <p className="text-[12.5px] leading-relaxed text-ink-700 mb-3">
                  {b.claude_blurb}
                </p>
                <div className="flex items-center justify-between text-[11px] mt-auto pt-2 border-t border-line">
                  <div>
                    <div className="text-ink-500">
                      {b.phase_gate_check.kpi_label}
                    </div>
                    <div className="mono font-semibold">
                      {b.phase_gate_check.actual}{" "}
                      <span className="text-ink-400 font-normal">
                        / {b.phase_gate_check.threshold}
                      </span>
                    </div>
                  </div>
                  <Sparkline
                    values={b.sparkline_values}
                    color={t.brand_color}
                    width={84}
                    height={26}
                  />
                </div>
              </Link>
            );
          })}
        </div>
      </section>

      {/* Top risks + KPI movements */}
      <section className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <div className="lg:col-span-2 panel p-5">
          <div className="flex items-center justify-between mb-3">
            <h2 className="section-title flex items-center gap-2">
              <AlertTriangle className="h-3.5 w-3.5 text-accent-amber" />
              Top risks — what I'm flagging up
            </h2>
            <span className="text-[11px] text-ink-500">
              {standup.top_risks.length} this week
            </span>
          </div>
          <ul className="divide-y divide-line">
            {standup.top_risks.map((r) => {
              const draft = escalationDrafts.find(
                (d) => d.draft_id === r.escalation_draft_id
              );
              const t = titles.find((x) => x.title_id === r.title_id);
              return (
                <li key={r.risk_id} className="py-3 first:pt-0 last:pb-0">
                  <div className="flex items-start gap-3">
                    <Badge tone={SEVERITY_TONE[r.severity]} size="xs">
                      {r.severity}
                    </Badge>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-baseline gap-2 flex-wrap">
                        <span className="text-[13.5px] font-semibold">
                          {r.headline}
                        </span>
                        {t && (
                          <span
                            className="text-[10px] uppercase tracking-wider font-semibold"
                            style={{ color: t.brand_color }}
                          >
                            {t.title_name}
                          </span>
                        )}
                      </div>
                      <p className="text-[12.5px] text-ink-700 mt-1">
                        {r.detail}
                      </p>
                      <p className="text-[12.5px] text-ink-900 mt-1.5">
                        <span className="text-[10px] uppercase tracking-wider font-semibold text-ink-500 mr-1.5">
                          Action
                        </span>
                        {r.recommended_action}
                      </p>
                      {draft && (
                        <button
                          type="button"
                          onClick={() => setActiveDraftId(draft.draft_id)}
                          className="mt-2 inline-flex items-center gap-1.5 text-[11.5px] text-accent-primary font-medium hover:underline"
                        >
                          <Send className="h-3 w-3" />
                          View Claude-drafted {draft.channel} to{" "}
                          {draft.recipient}
                        </button>
                      )}
                    </div>
                  </div>
                </li>
              );
            })}
          </ul>
        </div>

        <div className="panel p-5">
          <h2 className="section-title flex items-center gap-2 mb-3">
            <CircleDot className="h-3.5 w-3.5 text-accent-primary" />
            KPI movements
          </h2>
          <ul className="space-y-2.5">
            {standup.kpi_movements.map((m, i) => (
              <li
                key={i}
                className="flex items-center justify-between gap-3 text-[12.5px]"
              >
                <span className="text-ink-700 truncate">{m.kpi_label}</span>
                <div className="flex items-center gap-2 shrink-0">
                  <span className="mono font-semibold">{m.value}</span>
                  <span
                    className={`text-[11px] mono ${
                      m.direction === "up"
                        ? "text-accent-success"
                        : "text-accent-red"
                    }`}
                  >
                    {m.delta}
                  </span>
                </div>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* Suggested escalations strip */}
      <section className="panel p-5">
        <h2 className="section-title mb-3 flex items-center gap-2">
          <Send className="h-3.5 w-3.5 text-accent-violet" />
          Suggested escalations — drafted for review
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {standup.suggested_escalations.map((s) => {
            const draft = escalationDrafts.find(
              (d) => d.draft_id === s.escalation_draft_id
            );
            return (
              <button
                key={s.escalation_draft_id}
                type="button"
                onClick={() => draft && setActiveDraftId(draft.draft_id)}
                className="text-left border border-line rounded-lg p-3 hover:border-accent-primary hover:bg-accent-primary/[0.03] transition-all"
              >
                <div className="text-[10.5px] uppercase tracking-wider text-ink-500 font-semibold">
                  {s.channel} · {s.recipient}
                </div>
                <div className="text-[13px] font-medium mt-1.5 text-ink-900">
                  {s.summary}
                </div>
                <div className="text-[11px] text-accent-primary mt-2 flex items-center gap-1">
                  Open draft <ArrowUpRight className="h-3 w-3" />
                </div>
              </button>
            );
          })}
        </div>
      </section>

      <EscalationModal
        draft={activeDraft}
        onClose={() => setActiveDraftId(null)}
      />

      <footer className="text-[11px] text-ink-500 pt-4 pb-2 text-center">
        Demo data · 2K BeatBoard prototype · built with Claude Code
      </footer>
    </div>
  );
}
