"use client";

import Link from "next/link";
import { Sparkles, CheckCircle2, AlertTriangle, OctagonAlert, Clock } from "lucide-react";
import { titles, fmtDate } from "@/lib/data";

const STATUS_META = {
  on_track: {
    label: "On track",
    bucket: "on_track",
    icon: CheckCircle2,
    barClass: "bg-accent-success",
    chipClass: "bg-accent-success/10 text-accent-success border-accent-success/30",
    accent: "text-accent-success",
  },
  at_risk: {
    label: "At risk",
    bucket: "at_risk",
    icon: AlertTriangle,
    barClass: "bg-accent-amber",
    chipClass: "bg-accent-amber/10 text-accent-amber border-accent-amber/30",
    accent: "text-accent-amber",
  },
  blocked: {
    label: "Blocked",
    bucket: "blocked",
    icon: OctagonAlert,
    barClass: "bg-accent-red",
    chipClass: "bg-accent-red/10 text-accent-red border-accent-red/30",
    accent: "text-accent-red",
  },
  delayed: {
    label: "Delayed",
    bucket: "blocked",
    icon: Clock,
    barClass: "bg-accent-red",
    chipClass: "bg-accent-red/10 text-accent-red border-accent-red/30",
    accent: "text-accent-red",
  },
};

const BUCKETS = [
  { key: "on_track", label: "On track" },
  { key: "at_risk", label: "At risk" },
  { key: "blocked", label: "Blocked / delayed" },
];

export default function PortfolioHealthGrid({ summary }) {
  // Group titles into 3 buckets based on campaign_status. "delayed" collapses
  // into the "blocked" bucket so the user gets a 3-column scannable view.
  const grouped = BUCKETS.reduce((acc, b) => {
    acc[b.key] = titles.filter((t) => {
      const meta = STATUS_META[t.campaign_status];
      return meta && meta.bucket === b.key;
    });
    return acc;
  }, {});

  return (
    <section className="panel p-4 md:p-5 relative overflow-hidden space-y-4">
      <div className="absolute top-0 left-0 h-1 w-full bg-gradient-to-r from-twok-red via-accent-primary to-twok-red" />

      {/* Manager summary (Claude blurb) */}
      <div className="flex items-start gap-3">
        <div className="h-7 w-7 rounded-lg bg-twok-red/10 text-twok-red flex items-center justify-center shrink-0">
          <Sparkles className="h-3.5 w-3.5" />
        </div>
        <div className="min-w-0">
          <div className="text-[10.5px] uppercase tracking-wider text-ink-500 font-semibold">
            Portfolio health roll-up · generated by Claude
          </div>
          <p className="text-[13px] leading-relaxed mt-1 text-ink-700">
            {summary}
          </p>
        </div>
      </div>

      {/* 3-column status breakdown */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        {BUCKETS.map((b) => {
          const items = grouped[b.key] || [];
          const sample = items[0]
            ? STATUS_META[items[0].campaign_status]
            : STATUS_META[b.key === "blocked" ? "blocked" : b.key];
          const Icon = sample.icon;
          return (
            <div
              key={b.key}
              className="border border-line rounded-lg overflow-hidden"
            >
              <div className={`${sample.barClass} h-1`} />
              <div className="p-3">
                <div className="flex items-center gap-1.5 text-[11px] uppercase tracking-wider font-semibold">
                  <Icon className={`h-3 w-3 ${sample.accent}`} />
                  <span className={sample.accent}>{b.label}</span>
                  <span className="text-ink-500 ml-auto mono normal-case tracking-normal">
                    {items.length}
                  </span>
                </div>
                {items.length === 0 ? (
                  <div className="text-[11.5px] text-ink-400 italic mt-2">
                    None.
                  </div>
                ) : (
                  <ul className="mt-2 space-y-1.5">
                    {items.map((t) => (
                      <li key={t.title_id}>
                        <Link
                          href={`/titles/${t.franchise_slug}`}
                          className="flex items-center gap-2 text-[12px] hover:underline"
                        >
                          <span
                            className="h-2 w-2 rounded-full shrink-0"
                            style={{ backgroundColor: t.brand_color }}
                          />
                          <span className="font-medium text-ink-900 truncate">
                            {t.title_name}
                          </span>
                        </Link>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* Per-title mini cards */}
      <div>
        <div className="text-[10.5px] uppercase tracking-wider text-ink-500 font-semibold mb-2">
          By title · next milestone
        </div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
          {titles.map((t) => {
            const meta =
              STATUS_META[t.campaign_status] || STATUS_META.on_track;
            const Icon = meta.icon;
            return (
              <Link
                key={t.title_id}
                href={`/titles/${t.franchise_slug}`}
                className="border border-line rounded-lg p-2.5 hover:border-ink-300 transition-all block"
                style={{
                  borderLeft: `3px solid ${t.brand_color}`,
                }}
              >
                <div className="flex items-center justify-between gap-1.5">
                  <span
                    className="text-[11.5px] font-semibold text-ink-900 truncate"
                    title={t.title_name}
                  >
                    {t.title_name}
                  </span>
                  <span
                    className={`inline-flex items-center gap-0.5 text-[9.5px] uppercase tracking-wider font-bold px-1.5 py-0.5 rounded border ${meta.chipClass} shrink-0`}
                    title={meta.label}
                  >
                    <Icon className="h-2.5 w-2.5" />
                    {meta.label}
                  </span>
                </div>
                <div className="text-[10.5px] text-ink-500 mt-1 truncate">
                  {t.current_phase.replace(/_/g, " ")}
                </div>
                <div className="text-[10.5px] text-ink-700 mt-0.5 truncate">
                  Next:{" "}
                  <span className="font-medium">
                    {t.next_milestone_name}
                  </span>
                </div>
                <div className="text-[10px] text-ink-400 mono mt-0.5">
                  {fmtDate(t.next_milestone_date)}
                </div>
              </Link>
            );
          })}
        </div>
      </div>
    </section>
  );
}
